// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Valentyn Khoroshylov"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/exports/inventory": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exports"
                ],
                "summary": "Export Inventory to Google Sheets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by brand or model",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by brand name",
                        "name": "brand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by type (TIRE, RIM)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "URL of the Google Sheet",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/exports/pnl": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exports"
                ],
                "summary": "Export P\u0026L to Google Sheets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start Date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End Date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Warehouse ID",
                        "name": "warehouse_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "URL of the Google Sheet",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get all users with optional filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-admin"
                ],
                "summary": "List Users",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by username, phone, name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by role (BUYER, STAFF, ADMIN)",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Create new worker by Telegram ID or promote existing user by Username/Phone.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-admin"
                ],
                "summary": "Add Worker",
                "parameters": [
                    {
                        "description": "Worker details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateWorkerDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "delete": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Soft delete a user account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-admin"
                ],
                "summary": "Delete User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/role": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Promote or demote a user (e.g. BUYER -\u003e STAFF).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users-admin"
                ],
                "summary": "Update User Role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Role",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateUserRoleDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/warehouses": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Create Warehouse",
                "parameters": [
                    {
                        "description": "Warehouse details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateWarehouseDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/warehouses/{id}": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Update Warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateWarehouseDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Delete Warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/telegram": {
            "post": {
                "description": "Validates Telegram initData and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login via Telegram Mini App",
                "parameters": [
                    {
                        "description": "Telegram initData",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AuthRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/lots": {
            "get": {
                "description": "Get active lots. Purchase price and archive data are hidden.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-public"
                ],
                "summary": "List available lots (Public)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by brand or model",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by brand name",
                        "name": "brand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by type (TIRE, RIM)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by width (mm)",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by profile (%)",
                        "name": "profile",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by diameter (R)",
                        "name": "diameter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by season",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model name",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by condition (NEW/USED)",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by run flat parameter",
                        "name": "is_run_flat",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by spiked parameter",
                        "name": "is_spiked",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by anti puncture parameter",
                        "name": "anti_puncture",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Filter by exact sell price",
                        "name": "sell_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by exact quantity",
                        "name": "current_quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LotPublicResponse"
                            }
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get a paginated list of orders placed by the current user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "My Orders History",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.OrderResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Place a new order with customer details and tire items.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order details",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateOrderDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reports/pnl": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Calculates total revenue, COGS, and profit based on DONE orders.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get Profit \u0026 Loss Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start Date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End Date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Warehouse ID",
                        "name": "warehouse_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PnLReport"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/lots": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get lots including sensitive financial data and archives.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "List all lots (Internal)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by brand or model",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by brand name",
                        "name": "brand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by type (TIRE, RIM)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by width (mm)",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by profile (%)",
                        "name": "profile",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by diameter (R)",
                        "name": "diameter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by season",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by model name",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by condition (NEW/USED)",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by run flat parameter",
                        "name": "is_run_flat",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by spiked parameter",
                        "name": "is_spiked",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by anti puncture parameter",
                        "name": "anti_puncture",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Filter by exact sell price",
                        "name": "sell_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by exact quantity",
                        "name": "current_quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LotInternalResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Add a new lot to the inventory.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "Create a new lot",
                "parameters": [
                    {
                        "description": "Lot details",
                        "name": "lot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateLotDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/staff/lots/photo": {
            "delete": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Removes the image from MinIO using its public URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Delete a photo",
                "parameters": [
                    {
                        "description": "Public URL of the photo to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeletePhotoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/lots/upload": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Compresses the image to JPEG, uploads to MinIO, and returns the public URL.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "media"
                ],
                "summary": "Upload a photo",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the public URL of the uploaded image",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/lots/{id}": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Update details of an existing lot.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "Update a lot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lot update details",
                        "name": "lot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateLotDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Soft delete a lot.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "Delete a lot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/lots/{id}/qr": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Generates and returns a PNG image of a QR code containing the Lot ID.",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "lots-admin"
                ],
                "summary": "Get Lot QR Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lot ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PNG Image",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/orders": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get a paginated list of orders, filterable by status or customer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders-staff"
                ],
                "summary": "List Orders",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by customer name or phone",
                        "name": "customer",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.OrderResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/orders/{id}/status": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Change the status of an existing order (e.g., NEW, PREPAYMENT, DONE, CANCELLED).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Update Order Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status and comment",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateOrderStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/transfers": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get paginated list of transfers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "List Transfers",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source warehouse",
                        "name": "from_warehouse_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by destination warehouse",
                        "name": "to_warehouse_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TransferResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Moves stock from one warehouse to another (Status: IN_TRANSIT).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Create Transfer",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTransferDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/staff/transfers/{id}": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get transfer by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Get Transfer Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.TransferResponse"
                        }
                    }
                }
            }
        },
        "/staff/transfers/{id}/accept": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Receives the stock at the destination warehouse (Status: ACCEPTED).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Accept Transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/transfers/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Cancels an IN_TRANSIT transfer and refunds stock.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Cancel Transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/warehouses": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "List Warehouses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Warehouse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AuthRequestDTO": {
            "type": "object",
            "required": [
                "init_data"
            ],
            "properties": {
                "init_data": {
                    "description": "The raw string from window.Telegram.WebApp.initData",
                    "type": "string"
                }
            }
        },
        "domain.AuthResponseDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/domain.User"
                }
            }
        },
        "domain.CreateLotDTO": {
            "type": "object",
            "required": [
                "brand",
                "condition",
                "initial_quantity",
                "purchase_price",
                "sell_price",
                "type",
                "warehouse_id"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "USED"
                    ]
                },
                "defects": {
                    "type": "string"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "description": "URLs to images",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "purchase_price": {
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "TIRE",
                        "RIM"
                    ]
                },
                "warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateOrderDTO": {
            "type": "object",
            "required": [
                "customer_name",
                "customer_phone",
                "items"
            ],
            "properties": {
                "customer_name": {
                    "type": "string"
                },
                "customer_phone": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.OrderItemDTO"
                    }
                }
            }
        },
        "domain.CreateTransferDTO": {
            "type": "object",
            "required": [
                "from_warehouse_id",
                "items",
                "to_warehouse_id"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "from_warehouse_id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.TransferItemDTO"
                    }
                },
                "to_warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateWarehouseDTO": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "domain.CreateWorkerDTO": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "enum": [
                        "STAFF",
                        "ADMIN"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.UserRole"
                        }
                    ]
                },
                "telegram_id": {
                    "description": "Optional if searching by other fields",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.LotInternalResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "defects": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "purchase_price": {
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.LotParams": {
            "type": "object",
            "properties": {
                "anti_puncture": {
                    "type": "boolean"
                },
                "diameter": {
                    "type": "integer"
                },
                "is_run_flat": {
                    "type": "boolean"
                },
                "is_spiked": {
                    "type": "boolean"
                },
                "profile": {
                    "type": "integer"
                },
                "season": {
                    "description": "SUMMER, WINTER, ALL_SEASON",
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "domain.LotPublicResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "defects": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sell_price": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.OrderItemDTO": {
            "type": "object",
            "required": [
                "lot_id",
                "quantity"
            ],
            "properties": {
                "lot_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.OrderItemResponse": {
            "type": "object",
            "properties": {
                "lot_id": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "domain.OrderResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "customer_phone": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OrderItemResponse"
                    }
                },
                "status": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "domain.PnLReport": {
            "type": "object",
            "properties": {
                "by_warehouse": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.WarehousePnL"
                    }
                },
                "total_cogs": {
                    "type": "number"
                },
                "total_items_sold": {
                    "type": "integer"
                },
                "total_profit": {
                    "type": "number"
                },
                "total_revenue": {
                    "type": "number"
                }
            }
        },
        "domain.TransferItemDTO": {
            "type": "object",
            "required": [
                "lot_id",
                "quantity"
            ],
            "properties": {
                "lot_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.TransferItemResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "source_lot_id": {
                    "type": "string"
                }
            }
        },
        "domain.TransferResponse": {
            "type": "object",
            "properties": {
                "accepted_by": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "from_warehouse_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TransferItemResponse"
                    }
                },
                "status": {
                    "type": "string"
                },
                "to_warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.UpdateLotDTO": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "USED"
                    ]
                },
                "defects": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "purchase_price": {
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "TIRE",
                        "RIM"
                    ]
                },
                "warehouse_id": {
                    "description": "Optional: Move lot to another warehouse (inventory implication?)",
                    "type": "string"
                }
            }
        },
        "domain.UpdateOrderStatusDTO": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PREPAYMENT",
                        "DONE",
                        "CANCELLED"
                    ]
                }
            }
        },
        "domain.UpdateUserRoleDTO": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "enum": [
                        "BUYER",
                        "STAFF",
                        "ADMIN"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.UserRole"
                        }
                    ]
                }
            }
        },
        "domain.UpdateWarehouseDTO": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.UserRole"
                },
                "telegram_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.UserRole": {
            "type": "string",
            "enum": [
                "ADMIN",
                "STAFF",
                "BUYER"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleStaff",
                "RoleBuyer"
            ]
        },
        "domain.Warehouse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.WarehousePnL": {
            "type": "object",
            "properties": {
                "cogs": {
                    "type": "number"
                },
                "items_sold": {
                    "type": "integer"
                },
                "profit": {
                    "type": "number"
                },
                "revenue": {
                    "type": "number"
                },
                "warehouse_name": {
                    "type": "string"
                }
            }
        },
        "v1.DeletePhotoRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "RoleAuth": {
            "description": "Введите токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Tires Shop CRM API",
	Description:      "This is a REST API for managing a tires and rims store/warehouse.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
