// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Valentyn Khoroshylov"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/warehouses": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Create Warehouse",
                "parameters": [
                    {
                        "description": "Warehouse details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateWarehouseDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/warehouses/{id}": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Update Warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateWarehouseDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Delete Warehouse",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Warehouse ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/telegram": {
            "post": {
                "description": "Validates Telegram initData and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login via Telegram Mini App",
                "parameters": [
                    {
                        "description": "Telegram initData",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AuthRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AuthResponseDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/lots": {
            "get": {
                "description": "Get active lots. Purchase price and archive data are hidden.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-public"
                ],
                "summary": "List available lots (Public)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by brand name",
                        "name": "brand",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LotPublicResponse"
                            }
                        }
                    }
                }
            }
        },
        "/reports/pnl": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Calculates total revenue, COGS, and profit based on DONE orders.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get Profit \u0026 Loss Report",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PnLReport"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/lots": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Get lots including sensitive financial data and archives.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "List all lots (Internal)",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by brand name",
                        "name": "brand",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LotInternalResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Add a new lot to the inventory.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lots-staff"
                ],
                "summary": "Create a new lot",
                "parameters": [
                    {
                        "description": "Lot details",
                        "name": "lot",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateLotDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/staff/orders": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Place a new order with customer details and tire items.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order details",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateOrderDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/orders/{id}/status": {
            "put": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Change the status of an existing order (e.g., NEW, PREPAYMENT, DONE, CANCELLED).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Update Order Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New status and comment",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.UpdateOrderStatusDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/transfers": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Moves stock from one warehouse to another (Status: IN_TRANSIT).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Create Transfer",
                "parameters": [
                    {
                        "description": "Transfer details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTransferDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/staff/transfers/{id}/accept": {
            "post": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "description": "Receives the stock at the destination warehouse (Status: ACCEPTED).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transfers"
                ],
                "summary": "Accept Transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transfer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/staff/warehouses": {
            "get": {
                "security": [
                    {
                        "RoleAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "List Warehouses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Warehouse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AuthRequestDTO": {
            "type": "object",
            "required": [
                "init_data"
            ],
            "properties": {
                "init_data": {
                    "description": "The raw string from window.Telegram.WebApp.initData",
                    "type": "string"
                }
            }
        },
        "domain.AuthResponseDTO": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/domain.User"
                }
            }
        },
        "domain.CreateLotDTO": {
            "type": "object",
            "required": [
                "brand",
                "condition",
                "initial_quantity",
                "purchase_price",
                "sell_price",
                "type",
                "warehouse_id"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "USED"
                    ]
                },
                "defects": {
                    "description": "Description of damages, if any",
                    "type": "string"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "description": "URLs to images",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "purchase_price": {
                    "description": "Hidden from buyer",
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "TIRE",
                        "RIM"
                    ]
                },
                "warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateOrderDTO": {
            "type": "object",
            "required": [
                "customer_name",
                "customer_phone",
                "items"
            ],
            "properties": {
                "customer_name": {
                    "type": "string"
                },
                "customer_phone": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.OrderItemDTO"
                    }
                }
            }
        },
        "domain.CreateTransferDTO": {
            "type": "object",
            "required": [
                "from_warehouse_id",
                "items",
                "to_warehouse_id"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "from_warehouse_id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/domain.TransferItemDTO"
                    }
                },
                "to_warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.CreateWarehouseDTO": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "domain.LotInternalResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "defects": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initial_quantity": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "purchase_price": {
                    "type": "number"
                },
                "sell_price": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "warehouse_id": {
                    "type": "string"
                }
            }
        },
        "domain.LotParams": {
            "type": "object",
            "properties": {
                "anti_puncture": {
                    "type": "boolean"
                },
                "diameter": {
                    "type": "integer"
                },
                "is_run_flat": {
                    "type": "boolean"
                },
                "is_spiked": {
                    "type": "boolean"
                },
                "profile": {
                    "type": "integer"
                },
                "season": {
                    "description": "SUMMER, WINTER, ALL_SEASON",
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "domain.LotPublicResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "condition": {
                    "type": "string"
                },
                "current_quantity": {
                    "type": "integer"
                },
                "defects": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/domain.LotParams"
                },
                "photos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sell_price": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.OrderItemDTO": {
            "type": "object",
            "required": [
                "lot_id",
                "quantity"
            ],
            "properties": {
                "lot_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.PnLReport": {
            "type": "object",
            "properties": {
                "cogs": {
                    "description": "Cost Of Goods Sold (Purchase price)",
                    "type": "number"
                },
                "profit": {
                    "description": "Revenue - COGS",
                    "type": "number"
                },
                "revenue": {
                    "description": "Total sales amount",
                    "type": "number"
                }
            }
        },
        "domain.TransferItemDTO": {
            "type": "object",
            "required": [
                "lot_id",
                "quantity"
            ],
            "properties": {
                "lot_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.UpdateOrderStatusDTO": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PREPAYMENT",
                        "DONE",
                        "CANCELLED"
                    ]
                }
            }
        },
        "domain.UpdateWarehouseDTO": {
            "type": "object",
            "required": [
                "location",
                "name"
            ],
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 3
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.UserRole"
                },
                "telegram_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.UserRole": {
            "type": "string",
            "enum": [
                "ADMIN",
                "STAFF",
                "BUYER"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleStaff",
                "RoleBuyer"
            ]
        },
        "domain.Warehouse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "RoleAuth": {
            "description": "Введите токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Tires Shop CRM API",
	Description:      "This is a REST API for managing a tires and rims store/warehouse.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
